
name: tauri publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  # to clear the cache, change the value of CACHE_VERSION

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache stuff
        id: cache-tauri-build
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            src-tauri/target/
          key: ${{ runner.os }}-${{ secrets.CACHE_VERSION }}-tauri-build

      - name: Cache rust stuff
        id: cache-rust-stuff
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: ${{ runner.os }}-${{ secrets.CACHE_VERSION }}-rust-stuff


      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install webkit2gtk (ubuntu only)
        #if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: yarn build
        run: |
          yarn && yarn build

      - name: install bundler?
        run: |
          yarn global add @vue/cli
          cargo install tauri-bundler

      - name: tauri build
        run: |
          yarn tauri:build


      - name: stuff
        run: find src-tauri | tee src-tauri-files.txt

      # Upload artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: src-tauri/target/release/bundle


  create-release:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      RELEASE_UPLOAD_URL: ${{ steps.create_tauri_release.outputs.upload_url }}

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: get version
        run: echo ::set-env name=PACKAGE_VERSION::$(node -p "require('./package.json').version")

      - name: create release
        id: create_tauri_release
        uses: jbolda/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.package.name }}-v${{ env.PACKAGE_VERSION }}
          release_name: 'Release nota app v${{ env.PACKAGE_VERSION }}'
          body: 'See the assets to download this version and install.'
          draft: true
          prerelease: false

#  publish-tauri:
#    strategy:
#      fail-fast: false
#      matrix:
#        platform: [macos-latest, ubuntu-latest, windows-latest]
#
#    runs-on: ${{ matrix.platform }}
#    steps:
#    - uses: actions/checkout@v2
#    - name: setup node
#      uses: actions/setup-node@v1
#      with:
#        node-version: 12
#
#    - name: install Rust stable
#      uses: actions-rs/toolchain@v1
#      with:
#        toolchain: stable
#
#    - name: install webkit2gtk (ubuntu only)
#      if: matrix.platform == 'ubuntu-latest'
#      run: |
#        sudo apt-get update
#        sudo apt-get install -y webkit2gtk-4.0
#
#    - name: install app dependencies and build it
#      run: yarn && yarn build
#
#    - uses: tauri-apps/tauri-action@v0
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
#        releaseName: "App v__VERSION__"
#        releaseBody: "See the assets to download this version and install."
#        releaseDraft: true
#        prerelease: false


